trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DockerDownloadJob
  steps:
  - script: |
      # Atualize os pacotes do sistema
      sudo apt-get update
      
      # Instale o Docker
      sudo apt-get install -y docker.io
      
      # Inicie o serviço do Docker
      sudo service docker start
      
      # Adicione seu usuário ao grupo Docker para evitar usar sudo
      sudo usermod -aG docker $(whoami)
    displayName: 'Instalar Docker'
